install.packages("shiny")
install.packages("shinyalert")
install.packages("shinycssloaders")
install.packages("shinyjs")
install.packages("shinydashboard")
install.packages("htmltools")
install.packages("xml2")
install.packages("sf")
install.packages("leaflet")
install.packages("ggplot2")
install.packages("plotly")
install.packages("ncdf4")
install.packages("reshape")
install.packages("sortable")
install.packages("tinytex")
install.packages("rvest")
install.packages("rLakeAnalyzer")
install.packages("DT")
install.packages("rintrojs")
install.packages("hover")
install.packages("stringr")
install.packages("tidyr")
install.packages("RColorBrewer")
install.packages("ggpubr")
install.packages("readr")
install.packages("shinyBS")
install.packages("httr")
install.packages("plyr")
install.packages("lubridate")
install.packages("zoo")
install.packages("deSolve")
install.packages("reshape2")
install.packages("rmarkdown")
install.packages("remotes")
remotes::install_github('yonicd/slickR') # removed from CRAN - now only on GitHub


